baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'Arnav Patil'
theme = 'hermit-v2'

pygmentsCodefences  = true
pygmentsUseClasses  = true
rssLimit = 10

copyright = "CHANGE ME"
enableEmoji = true

[frontmatter]
date = ["date", "publishDate", "lastmod"]
lastmod = ["lastmod", ":git", "date", "publishDate"]
publishDate = ["publishDate", "date"]
expiryDate = ["expiryDate"]

[params]
    homeSubtitle = "Computer Engineering Student at the University of Toronto"
    footerCopyright = "Arnav Patil"
 
    dateform        = ""
    dateformShort   = ""
    dateformNum     = ""
    dateformNumTime = ""
    
    themeColor = "#494f5c"

    justifyContent = false

    relatedPosts = true
    code_copy_button = true

    homeSubtitlePrinter = true
    scrollToTop = true
    global_mathjax = true
    readTime = true
    readTimeSeparator = ""
    # legacyLayout = false
    shareSocial = true
    

    [[params.socialLinks]]
        name = "linkedin"
        url = "https://www.linkedin.com/in/arnavpatil/"
    
    [[params.socialLinks]]
        name = "github"
        url = "https://github.com/arnav-patil-12"

[menu]
    [[menu.main]]
        name = "About Me"
        url = "about/"
        weight = 10

    [[menu.main]]
        name = "Resume"
        url = "resume.pdf"
        weight = 40

    [[menu.main]]
        name = "Course Notes"
        url = "class-notes/"
        weight = 20
        
    [[menu.main]]
        name = "Blog"
        url = "posts/"
        weight = 30
